### ISSUE TITLE
Please Provide troubleshooting tips

### ISSUE THREAD

**Issue by Shelrothman** [danielkhan/building-bots-reservation#14]
Yesterday my branch was working and Resi was responding. Today, everything is running the same and there is no response from Resi at all, and I am unsure how to fix this. I confirmed that my code is just like yours. The debugging won't even catch it.
Please provide some tips for troubleshooting. Maybe a FAQ. 
And/or do you have any advice on how to go about troubleshooting getting no response from Resi?
Thank you

**Comment by Shelrothman** [comment]
I tested my wit.ai in the console and the response is coming back as expected. I'm just not clear where in the code can I look at to see why the app is not receiving it?

**Comment by danielkhan** [comment]
The best and easiest way to tackle this kind of problem is to walk through the code and simply use `console.log()` statements to see which data is available where.
In your case, I would log out the return statement by wit.ai. 
Can you check what's in `queryResult` [here](https://github.com/danielkhan/building-bots-reservation/blob/final/services/WitService.js#L10)

**Comment by Shelrothman** [comment]
@danielkhan Thank you so much for your response! I did as you suggested and added a console.log() on that line 10. 
I then tried making a reservation both through slack and directly on localhost... No luck..  Its as if that WitService method is not being hit, because the console-message did not appear anywhere at all, not even as undefined or null. 

Any chance you can take a quick look and see if I am missing anything? I have it all here: https://github.com/Q118/nodebot

Thank you!

**Comment by danielkhan** [comment]
Are you sure that ngrok (the reverse proxy that serves as the endpoint for slack) is still running? 
The fact that it worked one day and didn't the next indicates something along these lines.
Also, that the hook seems to be never called points in that direction.

**Comment by Shelrothman** [comment]
Yes ngrok was running during all of this. I'll likely try to start again from scratch

**Comment by danielkhan** [comment]
Let's try one more thing. If ngrok is running, you can access its web Interface - the address is shown when you start it on the console.
You should see the incoming request and if the request is successful. If no request comes in, you need to update the URL of the endpoint in Slack. It changes when you restart.

**Comment by Shelrothman** [comment]
That was the fix!! Thank you so much, I appreciate it. I can now finish up your course. 
Thank you! :)
